### ISSUE TITLE
Error downlading package `kafka_2.13-2.7.0.tgz` 

### ISSUE THREAD

**Issue by tcajee** [ashleykleynhans/ansible-role-kafka_connect#1]
Required package version `kafka_2.13-2.7.0.tgz` no longer exists at this endpoint:
"http://apache.is.co.za/kafka/2.7.0/kafka_2.13-2.7.0.tgz"

This leads to the following error:

```
TASK [ashleykleynhans.kafka_connect : KAFKA CONNECT | Untar kafka]
...
FAILED! => {"changed": false, "msg": "Failure downloading http://apache.is.co.za/kafka/2.7.0/kafka_2.13-2.7.0.tgz, HTTP Error 404: Not Found"}
```

The required package exists here:
https://archive.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz

Updating the `kafka_connect__mirror` var as follows should resolve this:
```
kafka_connect__mirror: "https://archive.apache.org/dist/kafka"

**Comment by ashleykleynhans** [comment]
Fixed
